# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pha.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'pha.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpha.proto\x12\x04otda\"e\n\x10\x41steroidFeatures\x12\t\n\x01\x65\x18\x01 \x01(\x01\x12\t\n\x01q\x18\x02 \x01(\x01\x12\t\n\x01h\x18\x03 \x01(\x01\x12\x0e\n\x06is_neo\x18\x04 \x01(\x08\x12\x12\n\nclass_code\x18\x05 \x01(\x05\x12\x0c\n\x04moid\x18\x06 \x01(\x01\"N\n\x12PredictionResponse\x12\x0e\n\x06is_pha\x18\x01 \x01(\x08\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x12\x13\n\x0b\x65xplanation\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"6\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cmodel_loaded\x18\x02 \x01(\x08\x32\x81\x01\n\rPhaClassifier\x12;\n\x07Predict\x12\x16.otda.AsteroidFeatures\x1a\x18.otda.PredictionResponse\x12\x33\n\x06Health\x12\x13.otda.HealthRequest\x1a\x14.otda.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pha_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ASTEROIDFEATURES']._serialized_start=19
  _globals['_ASTEROIDFEATURES']._serialized_end=120
  _globals['_PREDICTIONRESPONSE']._serialized_start=122
  _globals['_PREDICTIONRESPONSE']._serialized_end=200
  _globals['_HEALTHREQUEST']._serialized_start=202
  _globals['_HEALTHREQUEST']._serialized_end=217
  _globals['_HEALTHRESPONSE']._serialized_start=219
  _globals['_HEALTHRESPONSE']._serialized_end=273
  _globals['_PHACLASSIFIER']._serialized_start=276
  _globals['_PHACLASSIFIER']._serialized_end=405
# @@protoc_insertion_point(module_scope)
